### ISSUE TITLE
shell.run throw "[emerg] lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)" logs

### ISSUE THREAD

**Issue by yorkane** [openresty/lua-resty-shell#17]
# Reproduce:
```
location /  {
        content_by_lua_block {
	     ngx.say(require('resty.shell').run([[hostname]]))
	}
}

--error.log:
2021/06/08 17:27:10 [emerg] 1712#1721: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor) 
2021/06/08 17:27:10 [emerg] 1712#1721: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor) 
2021/06/08 17:27:10 [emerg] 1712#1721: lua pipe child close() socket 0.0.0.0:80 failed (9: Bad file descriptor)

```

# Environment:
nginx -V
nginx version: openresty/1.19.3.2
built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1) 
built with OpenSSL 1.1.1k  25 Mar 2021
TLS SNI support enabled
configure arguments: --prefix=/usr/local/openresty/nginx --with-cc-opt='-O2 -DNGX_LUA_ABORT_AT_PANIC -I/usr/local/openresty/zlib/include -I/usr/local/openresty/pcre/include -I/usr/local/openresty/openssl111/include' --add-module=../ngx_devel_kit-0.3.1 --add-module=../echo-nginx-module-0.62 --add-module=../xss-nginx-module-0.06 --add-module=../ngx_coolkit-0.2 --add-module=../set-misc-nginx-module-0.32 --add-module=../form-input-nginx-module-0.12 --add-module=../encrypted-session-nginx-module-0.08 --add-module=../srcache-nginx-module-0.32 --add-module=../ngx_lua-0.10.19 --add-module=../ngx_lua_upstream-0.07 --add-module=../headers-more-nginx-module-0.33 --add-module=../array-var-nginx-module-0.05 --add-module=../memc-nginx-module-0.19 --add-module=../redis2-nginx-module-0.15 --add-module=../redis-nginx-module-0.3.7 --add-module=../ngx_stream_lua-0.0.9 --with-ld-opt='-Wl,-rpath,/usr/local/openresty/luajit/lib -L/usr/local/openresty/zlib/lib -L/usr/local/openresty/pcre/lib -L/usr/local/openresty/openssl111/lib -Wl,-rpath,/usr/local/openresty/zlib/lib:/usr/local/openresty/pcre/lib:/usr/local/openresty/openssl111/lib' --with-cc='ccache gcc -fdiagnostics-color=always -g3' --with-pcre-jit --with-stream --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v2_module --without-mail_pop3_module --without-mail_imap_module --without-mail_smtp_module --with-http_stub_status_module --with-http_realip_module --with-http_addition_module --with-http_auth_request_module --with-http_secure_link_module --with-http_random_index_module --with-http_gzip_static_module --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-threads --with-compat --with-stream --with-http_ssl_module

**Comment by spacewander** [comment]
Fixed by https://github.com/openresty/lua-nginx-module/pull/1832

**Comment by yorkane** [comment]
The latest openresty/1.19.3.2  has not fix it yet?

**Comment by spacewander** [comment]
The latest is 1.19.9.1 RC1
http://openresty.org/en/ann-1019009001rc1.html

**Comment by yorkane** [comment]
> The latest is 1.19.9.1 RC1
> http://openresty.org/en/ann-1019009001rc1.html

Huge thanks
